const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    // Product
    GET_ALL_PRODUCT:'GET_ALL_PRODUCT',
    ADD_CART:'ADD_CART',
}

export default ACTIONS